### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Ashokkumar18** [FlorientR/laravel-gentelella#1]
there is an error occurred while running on window

![image](https://cloud.githubusercontent.com/assets/20434946/17829862/6d1bf3ce-66d9-11e6-98ec-a562584a06eb.png)
Warning: require(E:\work\htdocs\laravel-gentelella\bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in E:\work\htdocs\laravel-gentelella\bootstrap\autoload.php on line 17

Fatal error: require(): Failed opening required 'E:\work\htdocs\laravel-gentelella\bootstrap/../vendor/autoload.php' (include_path='.;E:\work\php\PEAR') in E:\work\htdocs\laravel-gentelella\bootstrap\autoload.php on line 17

**Comment by FlorientR** [comment]
Hi, 

Sorry for late.

What setup you have ? 

WIndows 7 ? 8 ? 10 ? 
Wamp ? Lamp ? Other ?
PHP Version ?

Bye
F.R
