### ISSUE TITLE
npm install --global bower gulp

### ISSUE THREAD

**Issue by hypermnesia** [FlorientR/laravel-gentelella#13]
'npm' is not recognized as an internal or external command, operable program or batch file

**Comment by hypermnesia** [comment]
![capture](https://cloud.githubusercontent.com/assets/23227104/19956726/ad3b6dfa-a1ca-11e6-81de-5e09f11ff90e.PNG)

**Comment by FlorientR** [comment]
Hi,

You need to install Node.js on your computer.

Florient R

**Comment by FlorientR** [comment]
Hi,

It's ok after install Node.js ?

Florient R
