### ISSUE TITLE
gentelella demo sites in laravel

### ISSUE THREAD

**Issue by janmhamburg** [FlorientR/laravel-gentelella#15]
I've installed laravel-gentelelella successfully. First changes (style of login, left and top bar etc.) were made easily. But for creating the content it would be great to see how the demo sites of Gentelella (https://colorlib.com/polygon/gentelella/index.html) were made. Is there a migration of the demo sites (including installed packages) in laravel? Or do you have any idea how to benefit from these demo sites? I spent a lot of time to install and integrate yajra datatable packages into laravel-gentelelella and now it doesn't look like the demo sites (e.g. some css classes aren't defined). It would be much easier to adapt the content from the demo sites ;) Thank you.

**Comment by FlorientR** [comment]
Hi,

laravel-gentelella have all of component that include the gentelella framework. If you want create your page with add-on like yajra, you need to add your .css and .js into gulpfile and include the file with asset (A basic laravel). Then, you can copy/paste the code of gentelella demo in your application.



First : Search your add-on on the bower folder
![1](https://cloud.githubusercontent.com/assets/16555128/20008913/a6319e7a-a2a2-11e6-8638-ed588d1cd755.PNG)

Second, add your files into the gulpfile
![2](https://cloud.githubusercontent.com/assets/16555128/20008991/0045c58a-a2a3-11e6-82c2-a291ab529c78.PNG)

Next, run ```gulp``` on your application folder

Finally, add your asset on your page
![3](https://cloud.githubusercontent.com/assets/16555128/20009079/61df3916-a2a3-11e6-9436-bb1eada4b4e0.PNG)

And you are ready for use the add-on ! ;)

Bye,
Florient R

**Comment by FlorientR** [comment]
Hi,

It's ok for you ?

Florient R

**Comment by janmhamburg** [comment]
Yes. Thank you!
