### ISSUE TITLE
Drop in compatibility?

### ISSUE THREAD

**Issue by The1NdNly** [FlorientR/laravel-gentelella#16]
Hey dude, i love the fact you made a ready to go intergeneration  with laravel, but is there any reason you didn’t make it drop in like https://github.com/acacha/adminlte-laravel
i'm guessing it would be less updates needed + you can just drop it into a project your working on rather than have to merge this with your current project.

Bar that i love it dude, Thankyou!

**Comment by FlorientR** [comment]
Hi and thanks for your feedback !

https://github.com/acacha/adminlte-laravel is a complexe installation of Laravel and AdminLTE.

Laravel-gentelella is make for install a fresh Laravel with Gentelella template, for begin new project most rapidly. I don't think that this method is ok for laravel-gentelella but if you want, you can make a repo like adminlte-laravel using laravel-gentelella repo ;)

Thanks and good luck !

**Comment by The1NdNly** [comment]
I think I’m going to try and manually install it using your commits as a rough guide. Think it will be easer than trying to merge the two :)

if you take alook at https://github.com/acacha/adminlte-laravel its basically just replaces the out of the box views with a admin theme. its not a complete laravel project like your repo, rather something you can just "paste" over your current project with the bare files needed for the theme. just means you have to make a new laravel project before you pull it - makes it more usable :)


Best regards! Matt

**Comment by FlorientR** [comment]
If you want just "paste" the template views, you can copy the view from GitHub and paste in your app, just install gentelella with bower or change <link> and <script> ;)

I wait your feedback !
Bye, Florient R
