### ISSUE TITLE
Jquery issue

### ISSUE THREAD

**Issue by AasirR** [FlorientR/laravel-gentelella#17]
Before you publish this i began working with Gentelella on Laravel 5.2
Since I'm a beginner on laravel I have no idea on Gulp. So I included scripts but jquery doesn't work in my views. I do have to re include it. But when I re include it affects my side bar sliding.
Please help me.

**Comment by FlorientR** [comment]
Hi,

You can learn to use Gulp with Laravel, i'ts not difficult ;) 
All it's explain here : https://laravel.com/docs/5.3/elixir . And the part where explain the Elexir copy is here https://laravel.com/docs/5.3/elixir#copying-files-and-directories

Bye
Florient R

**Comment by AasirR** [comment]
Thank you
