### ISSUE TITLE
webpack to combine resources

### ISSUE THREAD

**Issue by Remo** [FlorientR/laravel-gentelella#18]
Any reasons not to use webpack? Would make it easy to create a single JavaScript file and also offer the ability to use modern ES features.
I'm no webpack expert, but if I find some time and if you're open to it, I'd put it on my todo list.

**Comment by FlorientR** [comment]
Hi,

I don't know "webpack" so if you want to integrate in laravel-gentelella, you can make a request ? ;)

Bye

**Comment by Remo** [comment]
I think it's not as easy as I thought. While gentelella is nice, it doesn't seem to properly support these techniques. I'll have to wait to get some feedback on this issue: https://github.com/puikinsh/gentelella/issues/315
