### ISSUE TITLE
How to integrate a date picker

### ISSUE THREAD

**Issue by janmhamburg** [FlorientR/laravel-gentelella#19]
Hi, on https://colorlib.com/polygon/gentelella/form.html there is a date-picker (Date of birth). It's just a field with class="date-picker...". Unfortunately, this class is not included in gentelella.min.css or bootstrap.min.css. But I've found some .daterangepicker styles in gentelella.min.css. Which scripts (and perhaps other css) do I have to integrate to make it work?

Thanks! Jan
(sorry for the edits ;)

**Comment by FlorientR** [comment]
Hi, 

If you want use DatePicker, you need to add the datepicker.js on your page.
See https://github.com/FlorientR/laravel-gentelella/issues/15#issuecomment-259065784

Bye ;)
Florient R

**Comment by FlorientR** [comment]
It's ok for the installation of DatePicker ? ;)

**Comment by janmhamburg** [comment]
Yes, thanks

**Comment by pdvbalaji** [comment]
Hi ,
I am using gentelella Alela UI , I am facing problem with data picker , I add daterangepicker.js,moment.min.js also but date picker is not working please help me
