### ISSUE TITLE
Missing components?

### ISSUE THREAD

**Issue by marcolino** [FlorientR/laravel-gentelella#20]
After installing, registering an account and logging in, I get these 404's:

GET http://myserver/vendors/iCheck/skins/flat/green.css  404 (Not Found)
GET http://myserver/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css  404 (Not Found)
GET http://myserver/css/maps/jquery-jvectormap-2.0.3.css  404 (Not Found)
GET http://myserver/images/img.jpg 404 (Not Found)

and only the sidebar is shown, the main panel on the right is blank.

I suppose it's just a configuration issue, since - for example - I have 'green.css' file in 'vendor/bower_components/gentelella/vendors/iCheck/skins/flat/green.css', and not in 'vendors/iCheck/skins/flat/'...

Do I miss some installation step, or some configuration in '.env', perhaps?
My .env contains
    APP_ENV=local
    APP_DEBUG=true
    APP_KEY=base64:...
    APP_URL=http://myserver
    ...

Thanks in advance, and keep up with this great project!

**Comment by FlorientR** [comment]
Hi,

This file is use in the Home page of Gentelella exemple and I have "clear" the page for a new page. I have forget this link, I correct this now.

The center of the page are empty and it's voluntary.

Bye,
Flo R

**Comment by marcolino** [comment]
Perfect, thanks. Perhaps you should specify in the README the default output will be blank, and not like the template demo, to avoid confusion... :-)

**Comment by FlorientR** [comment]
Yes I add this ;)

Thanks !
