### ISSUE TITLE
help with ui components

### ISSUE THREAD

**Issue by jonathanrcarter** [FlorientR/laravel-gentelella#24]
Hi I am familiar with the gentella ui  but I did not use laravel before.

Is there somewhere you have got the ui components already available for use as functions or modules? 

Otherwise I can make each component type as a layout (I think) but is this best?

**Comment by FlorientR** [comment]
Hi,

All components of Gentelella are already available on the repo.
You can follow steps of issue #15 for add your component.

Bye,
Flo R

**Comment by FlorientR** [comment]
Hi and happy new year !

It's ok for you with components ?

Flo R

**Comment by jonathanrcarter** [comment]
perfect , I really just got round to adding a component and it worked just fine !
