### ISSUE TITLE
Package working but not styled properly

### ISSUE THREAD

**Issue by rohan2812** [FlorientR/laravel-gentelella#25]
Hi,

I've installed the package following the instructions. After the installation the package works and I can log in to the admin panel. But the style is not properly loaded. Did I miss something. If I follow the css link, it shows the css file of bootstrap correctly.

**Comment by FlorientR** [comment]
Hi,

Can I have a screenshot please ?

Flo R

**Comment by rohan2812** [comment]
Hi Flo R,

Thank you for your quick response. I deleted my project and tried again for a third time and now it worked. Probably I did something wrong during the installation.

Rohan.
