### ISSUE TITLE
Problem with User model

### ISSUE THREAD

**Issue by renomx** [FlorientR/laravel-gentelella#26]
First of all.... Great job!

I cloned your project yesterday and begin to play with it a little. The first thing I have noticed is that there is a Models directory now and the User model was moved in there.

The little problem I found is that when you try to register as a new user, the register controller is looking for the User model under App\User to fix the error just modify the use call to fetch the model from the correct namespace as use App\Models\User;

Thanks and keep up the good work!

**Comment by FlorientR** [comment]
Hi and thanks !

I check and fix that ;)

Bye,
Flo R
