### ISSUE TITLE
npm install fails

### ISSUE THREAD

**Issue by yaoshanliang** [FlorientR/laravel-gentelella#29]
iat@iat-mbp:~/workspace/code/docker/laravel-gentelella (master)$ npm install
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm ERR! Darwin 16.3.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10

npm ERR! shasum check failed for /var/folders/tz/545tf5x52cbgx5x05ygt3v0m0000gn/T/npm-25832-5ca7393e/registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm ERR! Expected: a5f13ff79ef3b740fe30aa803fb09f98805d4782
npm ERR! Actual:   0659d42204e0b12c1f471213965374959cbf4ff8
npm ERR! From:     https://registry.npmjs.org/rx/-/rx-4.1.0.tgz
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/iat/workspace/code/docker/laravel-gentelella/npm-debug.log

**Comment by FlorientR** [comment]
Hi !

Please test that solution : https://github.com/FlorientR/laravel-gentelella/issues/27

Bye,
Flo R

**Comment by FlorientR** [comment]
Problem resolved ?
