### ISSUE TITLE
How to work with the lib

### ISSUE THREAD

**Issue by avifatal** [FlorientR/laravel-gentelella#40]
Hi 
I have installed the `laravel-gentelella` successfully,
What now? how do I work with that?
How do I take advantage of all the theme features?

Thanks

**Comment by FlorientR** [comment]
Hi,

I'ts an empty laravel project, like a new procject laravel 5.4.

For the theme, you should read the documentation. All feature of this theme are in laravel-gentelella.

Bye,
Flo R
