### ISSUE TITLE
Smartresize and tooltip is not a function

### ISSUE THREAD

**Issue by cristiangil** [FlorientR/laravel-gentelella#43]
Hi! I has been problems with this two functions. First of all sorry if I don't explain very well, my english is a bit poor.

Well, I've found with this mistake, I suppose that the problem is my app.js, I've app.js, custom.js and helper.js created by webpack.mix.js

The problem could be that jquery is redeclarated and some functions can be found with the error that "is not a function" I don't know if I could mix both files or avoid to generate jquery in custom.js.

However, mistake could be another. I newer in Laravel and I can do some by the wrong way.

Thanks

**Comment by FlorientR** [comment]
Hi and sorry for response time.

Jquery is in the end of resouces/view/layouts/blank.blade.php. Delete this line if your custom.js contains already Jquery.

Bye, FloR
