### ISSUE TITLE
Mixing views with Backpack CRUD

### ISSUE THREAD

**Issue by vekost** [FlorientR/laravel-gentelella#46]
Hello @FlorientR,

First of all, nice job integrating Gentelella theme in Laravel 5.4. I'd like to use it side by side with [https://github.com/Laravel-Backpack/CRUD](https://github.com/Laravel-Backpack/CRUD). However, the latter one is already using a blank Admin LTE package, so is it feasible to override their views with yours or it's going to be easier restyling and enhancing their views with Gentelella?

Thanks in advance!

**Comment by FlorientR** [comment]
Hi and thanks,

This package is very interesting ! I check that and I'll keep you informed ;)

Bye, FloR
