### ISSUE TITLE
compact menu, third level fail to open

### ISSUE THREAD

**Issue by Giambapisasale** [FlorientR/laravel-gentelella#48]
Hi, after click to compacting side menu, I cannot open a third level menu because on click to second level it collapse
![image](https://cloud.githubusercontent.com/assets/8735065/26444341/52a7b148-413c-11e7-8003-ff626a7150e8.png)
In the image you can see, if I click on "level one" the menu collapse instaed of open the third level

thanks

**Comment by FlorientR** [comment]
Hi,

The issue is on the Gentelella template (see https://colorlib.com/polygon/gentelella/). Please make the issue on https://github.com/puikinsh/gentelella/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen

Bye, FloR

**Comment by FlorientR** [comment]
https://github.com/puikinsh/gentelella/issues/490

**Comment by jahstation** [comment]
how can I use this solution over your implementation? i cannot find the file mention inside this post!
