### ISSUE TITLE
installed nothing

### ISSUE THREAD

**Issue by ttimt** [FlorientR/laravel-gentelella#49]
So I installed and there's no pages like dashboard and such? Or which installation part I did wrong? Or that's the meaning of "homepage is empty", then how do I add them in? is there a doc?

**Comment by FlorientR** [comment]
Hi,

Yes the home page is empty. All gentelella components are charged on vendor. You take only components you need. See this issue for more information https://github.com/FlorientR/laravel-gentelella/issues/15

Bye,
FloR

**Comment by ttimt** [comment]
ok thanks
