### ISSUE TITLE
how to install dependences... Unable to install it using bower on windows

### ISSUE THREAD

**Issue by smtc7648** [FlorientR/laravel-gentelella#50]
Hey there, greetings from smit parmar,
I'm smit and i was tired... Because i got a warning ⚠ when i try to install dependences using bower command... I got the message like instead of this try yarn or webpake when  i run the command "bower install"....
Please help me....
How can i add it with yarn and i get the simple view as an output without any style....

I'll look forward for your answer...

Thank you...

**Comment by FlorientR** [comment]
Hi,

What the message of the warning ?

**Comment by smtc7648** [comment]
hello,

i'm getting following message...


"
npm WARN deprecated bower@1.8.0: ..psst! While Bower is maintained, we recommend yarn and webpack for new front-end projects! Please read our blog for more.
"

**Comment by FlorientR** [comment]
Bower want use webpack but is not on laravel-gentellela. See https://github.com/FlorientR/laravel-gentelella/issues/18 . 

It's a warning so you can work with this ;)

Bye !

**Comment by FlorientR** [comment]
Hi,

It's ok for you ?
