### ISSUE TITLE
Lost Data

### ISSUE THREAD

**Issue by secrethash** [FlorientR/laravel-gentelella#53]
Referring to #52 

I lost my custom CSS, JS and some images. I was git pushing the project to a private repository. My laptop got broken from which I was doing my work. I thought the back was already made and all I needed was just to clone it in my new PC. When I cloned it, the public directory was not there and all my data in the public directory was lost.

Don't know why you have put that there but it is not at all necessary.

**Comment by clipvui2512** [comment]
Me too :( missing css file

**Comment by FlorientR** [comment]
Hi, sorry for this...... I merge this ;)
