### ISSUE TITLE
Class '\App\Models\User' not found

### ISSUE THREAD

**Issue by deeKodar** [FlorientR/laravel-gentelella#58]
After successfully downloading all the dependencies, I was able to run the login screen. After creating a user from the register form, Class '\App\Models\User' not found error came. I checked in the models directory the User class exists.
I have attached the error screen shot.
Any solution to it? Thanks in advance.

<img width="1296" alt="screen shot 2017-07-23 at 7 32 37 pm" src="https://user-images.githubusercontent.com/15119748/28499698-96753f10-6fdd-11e7-9937-884c79438030.png">

**Comment by FlorientR** [comment]
Hi

Can you make a `composer --dump-autoload` please ?

**Comment by FlorientR** [comment]
It's ok for you ?
