### ISSUE TITLE
Changing default bcrypt password check to md5

### ISSUE THREAD

**Issue by mariofonteles** [FlorientR/laravel-gentelella#62]
I'm currently on Laravel 5.4 and using this template's authentication. Problem is my whole project's password encryption is md5. This creates conflicts as Gentelella uses bcrypt for encryption. So currently i'm unable to login to any user created with md5 passwords. Is there a way to redefine the login/auth controller to check for md5 passwords and not bcrypt?

**Comment by UnderDogg** [comment]
Mario can you not convert the md5 passwords to bcrypt? MD5 is old and crackable
