### ISSUE TITLE
CSS / JS files missing

### ISSUE THREAD

**Issue by mas18** [FlorientR/laravel-gentelella#65]
Is it possible that the JS / CSS files are missing?

**Comment by FlorientR** [comment]
Are you enter "gulp" command ?

**Comment by mas18** [comment]
Yes but it didn't work:

Fetching Copy Source Files...
   - vendor/bower_components/gentelella/vendors/font-awesome/css/font-awesome.min.css <-- Not Found

**Comment by FlorientR** [comment]
Are you enter "bower install" ?

**Comment by mas18** [comment]
I think there's the error, but i don't know how to fix it. After the command "bower install" i get this message: bower gentelella#^1.4.0         ENOGIT git is not installed or not in the PATH

**Comment by FlorientR** [comment]
You can fix it with this link -> https://stackoverflow.com/questions/20666989/bower-enogit-git-is-not-installed-or-not-in-the-path

**Comment by mas18** [comment]
Thank you very much, fixed it with using git shell instead of cmd

**Comment by FlorientR** [comment]
Good ;)

By and thank's for use laravel-gentelella !
